include: package:flutter_lints/flutter.yaml

# https://dart-lang.github.io/linter/lints/index.html
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    depend_on_referenced_packages: false

analyzer:
