name: listview_utils
description: Infinite scrolling list view with multiple data source mode support using adapters. Also supports header, footer widgets.
version: 0.1.6+1
homepage: https://github.com/TheMisir/flutter-listutils

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # A mixture between dependency injection and state management, built with
  # widgets for widgets.
  provider: ^4.0.0

  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter