name: listutils
description: This package adds additional features (infinite scrolling, loading widgets, header, footer, adapter support) to flutter's ListView widget.
version: 0.0.3
homepage: https://github.com/TheMisir/flutter-listutils

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # A mixture between dependency injection and state management, built with
  # widgets for widgets.
  provider: ^4.0.4

  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter